on:  [push]

jobs:
  my-job:
    runs-on:  ubuntu-latest

    steps:
    - uses:  actions/checkout@v2
    - name:  runt the action
      id:  hello
      uses: ./
      with:
        myInput:  'great to use'
    - name:  output
      run:
        echo ${{ steps.hello.outputs.memory }}
        echo "total memory succesfully outpuy"
